# Generated by Django 4.2.1 on 2023-06-07 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='会话时间')),
                ('chat_content', models.TextField(verbose_name='完整对话')),
            ],
        ),
    ]
