# Generated by Django 4.2.1 on 2023-06-04 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=50, verbose_name='提示词分类')),
                ('prompt_template', models.TextField(verbose_name='提示词模板')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建用户id')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
    ]
