# Generated by Django 4.2.1 on 2023-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(max_length=20, verbose_name='法律名称')),
                ('law_sub', models.CharField(max_length=20, verbose_name='法律子项')),
                ('law_point', models.CharField(max_length=50, verbose_name='法律考点')),
            ],
        ),
    ]
